# This is a workflow to upload artifacts or files 

# https://github.com/marketplace/actions/upload-a-build-artifact
# https://github.com/actions/download-artifact

name: This is first action flow   # this is the name of the workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 uploadArtifactJob:
  runs-on: ubuntu-latest
  steps:
    - run: mkdir -p /tmp
    - run: echo hello > /tmp/world.txt
    - uses: actions/upload-artifact@v4
      with:
       name: my-artifact
       path: /tmp/world.txt
 downloadArtifactJob:
   runs-on: ubuntu-latest
   needs: uploadArtifactJob
   steps:
   - name: download the atricfact that has been generated in above stage
     uses: actions/download-artifact@v4
     with:
      name: my-artifact 

    
